### ISSUE TITLE
不同系统Hook 失败

### ISSUE THREAD

**Issue by mikelhm** [shaomaicheng/memoryescape#1]
三星6.0 hook 失败了，只有Region space 成功。
![image](https://github.com/shaomaicheng/memoryescape/assets/10327642/5655f5b8-f4e5-4609-9d01-2c9709c97c0f)

而使用另外一台12的手机 其他Hook 成功，只有 Region space 失败，
![image](https://github.com/shaomaicheng/memoryescape/assets/10327642/e6ce542c-4feb-4ee7-a087-688a0e915051)

符合预期吗

**Comment by zhang8615050** [comment]
有没有可能不同版本hook的符号不同？需要适配？

**Comment by shaomaicheng** [comment]
6.0我印象里不是regionspace吧

**Comment by shaomaicheng** [comment]
regionspace的alloc hook我只是看看实际小对象分配在哪里。和大对象分配修改计数这个无关哈
